// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
	"Meta": {
		"title": "Next Start",
		"description": "全栈 Next.js 项目模板"
	},
	"Nav": {
		"mainNav": "主导航",
		"dashboard": "概览",
		"notes": "笔记",
		"settings": "设置",
		"loading": "页面加载中"
	},
	"Account": {
		"signOut": "退出登录",
		"signOutTitle": "确认退出登录？",
		"signOutBody": "退出后需要重新用手机号和验证码登录。",
		"signOutConfirm": "确认退出",
		"cancel": "取消"
	},
	"ColorMode": {
		"light": "浅色",
		"dark": "深色",
		"switchTo": "切换到{mode}",
		"switchToAria": "切换到{mode}模式"
	},
	"Locale": {
		"label": "语言",
		"switchLanguage": "切换语言",
		"zh": "简体中文",
		"en": "English"
	},
	"Dashboard": {
		"eyebrow": "Mantine · 主题与组件",
		"title": "设计系统一览",
		"description": "这一页把主题里的色阶和常用组件摆出来。Mantine 的主题是一个 JS 对象，改 <code>src/components/providers/theme.ts</code> 就能看到全部组件跟着变。",
		"stats": {
			"layout": {
				"label": "布局",
				"value": "导航栏",
				"hint": "侧边栏 + 内容区 + 过渡动画"
			},
			"theme": {
				"label": "主题",
				"value": "CSS 变量",
				"hint": "语义色角色，明暗自动适配"
			},
			"platform": {
				"label": "平台",
				"value": "Web + SSR",
				"hint": "服务端组件与客户端组件共用一套样式"
			}
		},
		"palette": {
			"title": "颜色与色阶",
			"note": "Mantine 的每个颜色都是 0–9 十级色阶，组件的 variant 从色阶推导；theme.primaryColor 决定整套 UI 用哪一组"
		},
		"buttons": {
			"title": "按钮",
			"note": "Mantine 的 variant 系统：filled / light / outline / subtle / default，颜色由 color 单独决定"
		},
		"chips": {
			"title": "标签与消息",
			"note": "Badge 用于状态展示；notifications.show() 取代了 toast，前提是挂了一个 Notifications 组件",
			"default": "默认",
			"live": "已上线",
			"buildFailed": "构建失败",
			"archived": "已归档",
			"toastTrigger": "成功消息",
			"toastSuccess": "部署完成",
			"toastDangerTrigger": "失败消息",
			"toastDanger": "部署失败，请查看日志"
		},
		"form": {
			"title": "表单控件",
			"note": "TextInput 自带 label / description / error 三个槽位，不用自己拼",
			"projectName": "项目名称",
			"remark": "备注",
			"remarkPlaceholder": "可留空",
			"notify": "接收构建通知"
		},
		"controls": {
			"title": "选择与进度",
			"note": "SegmentedControl / Slider / Progress，给一个 data 数组就行，不用逐个写子组件",
			"compact": "紧凑",
			"comfortable": "适中",
			"spacious": "宽松",
			"volumeLabel": "音量",
			"volume": "音量 {value, number}%",
			"buildProgress": "构建进度"
		},
		"surfaces": {
			"title": "提示与浮层",
			"note": "Alert 的语义色，以及 Tooltip",
			"alertTitle": "这是一条 {status} 提示",
			"alertBody": "Alert 的配色来自 color 指定的那组色阶，换主题时不用改这里。",
			"tooltipTrigger": "悬停看提示",
			"tooltipBody": "Tooltip 由 floating-ui 驱动，默认只在悬停时出现"
		}
	},
	"Notes": {
		"title": "笔记",
		"description": "模板自带的完整示例：SQLite 表 → drizzle service → Server Action（连搜索和乐观更新也是）→ Mantine 界面。不需要的话整个域可以删掉。",
		"titleLabel": "标题",
		"titlePlaceholder": "想记点什么？",
		"bodyLabel": "内容",
		"bodyPlaceholder": "可留空",
		"submit": "添加",
		"created": "已添加",
		"titleInvalid": "标题必填，最多 200 个字符",
		"bodyInvalid": "内容最多 5000 个字符",
		"createFailed": "添加失败",
		"updateFailed": "更新失败",
		"deleteFailed": "删除失败",
		"searchLabel": "搜索笔记",
		"searchPlaceholder": "按标题搜索（大小写无关）",
		"toggleLabel": "把「{title}」标记为完成或未完成",
		"deleteLabel": "删除「{title}」",
		"empty": "还没有笔记",
		"emptyHint": "用上面的表单添加第一条。",
		"noResults": "没有匹配的笔记",
		"loadMore": "还有 {remaining, number} 条，加载更多",
		"noResultsHint": "换个关键词试试。",
		"searchClear": "清空搜索"
	},
	"Settings": {
		"title": "设置",
		"description": "占位页面。新增页面：在 src/app/[locale]/(app) 下建目录，然后到 src/components/layout/NavLinks.ts 加一条导航项。",
		"appearance": {
			"title": "外观",
			"current": "当前生效：{mode}",
			"followingSystem": "（跟随系统）",
			"system": "跟随系统",
			"light": "浅色",
			"dark": "深色"
		},
		"notifications": {
			"title": "通知",
			"note": "占位开关，接上你自己的偏好存储即可",
			"buildDone": "构建完成时通知我",
			"deployFailed": "部署失败时通知我",
			"weeklyDigest": "每周汇总邮件"
		}
	},
	"Login": {
		"title": "手机号登录",
		"phoneLabel": "手机号",
		"phonePlaceholder": "请输入手机号",
		"phoneInvalid": "请输入正确的手机号",
		"codeLabel": "验证码",
		"codePlaceholder": "6 位验证码",
		"codeInvalid": "请输入 6 位验证码",
		"sendCode": "获取验证码",
		"resendIn": "{seconds, number} 秒后重发",
		"demoCodeToast": "演示环境验证码固定为 {code}",
		"subscribeLabel": "接收产品更新和使用技巧",
		"termsPrefix": "继续即代表同意",
		"privacyPolicy": "《隐私政策》",
		"termsConjunction": "与",
		"termsOfService": "《服务条款》",
		"submit": "登录",
		"invalidCredentials": "验证码不正确。",
		"demoHint": "演示手机号 {phone}，验证码固定 {code}",
		"divider": "或",
		"wechatButton": "微信登录（未接入）"
	},
	"LoginHero": {
		"brand": "NEXT START",
		"tabPrimary": "快速开始",
		"tabSecondary": "示例代码",
		"cardBody": "一套现成的全栈骨架：Mantine + Drizzle/SQLite + Auth.js + next-intl。删掉示例业务，剩下的就是你的新项目。",
		"tagAuth": "认证",
		"tagDb": "数据库",
		"tagI18n": "国际化",
		"tagTheme": "主题",
		"headlineLine1": "距离启动下一个项目",
		"headlineLine2": "只差一次搭建"
	},
	"Errors": {
		"forbidden": "你的账号没有这个页面的访问权限。需要的话找管理员开通。",
		"notFound": "这个地址没有对应的页面。检查一下链接，或者回到首页重新开始。",
		"backHome": "回到首页",
		"title": "这个页面没能加载出来",
		"description": "渲染时出了点问题。重试一次通常就好了；如果一直这样，把下面的错误编号发给我们。",
		"retry": "重试",
		"digest": "错误编号 {digest}",
		"code": {
			"VALIDATION": "填写的内容不符合要求，检查一下再提交。",
			"UNAUTHORIZED": "登录状态已经失效，请重新登录。",
			"FORBIDDEN": "你没有做这个操作的权限。",
			"NOT_FOUND": "要操作的内容不存在，可能已经被删掉了。",
			"CONFLICT": "和已有的数据冲突，换一个值试试。",
			"RATE_LIMITED": "操作太频繁了，过一会儿再试。",
			"INTERNAL": "服务器出了点问题，稍后重试。"
		}
	}
};
export default messages;