import type { MetadataRoute } from 'next'
import { siteUrl } from '@/core/site-url'

/**
 * Served at /robots.txt.
 *
 * Lives at `src/app/robots.ts`, outside `[locale]` — robots.txt is per *origin*,
 * not per locale, so putting it inside the locale segment would publish it at
 * `/en/robots.txt` where no crawler looks.
 *
 * The disallow list is the interesting part. Everything here is either private or
 * pointless to index, and leaving any of it crawlable is a small but real leak:
 *
 * - `/api/` — no HTML, and `/api/auth/*` responses would be indexed with query
 *   strings that can contain tokens.
 * - `/login` — nothing to rank, and an indexed sign-in page attracts credential
 *   stuffing traffic.
 * - `/403` — an error page in search results is pure noise.
 *
 * **This is not access control.** A well-behaved crawler obeys it; nothing else
 * has to. The actual guard for private routes is the session check in
 * `app/[locale]/(app)/layout.tsx`.
 *
 * Note that the signed-in area (`/dashboard`, `/notes`, `/settings`) is *not*
 * listed: it already redirects anonymous visitors to `/login`, so a crawler gets
 * nothing. Add entries here if you ever make part of it public but unindexable.
 */
/**
 * `force-dynamic` so `APP_URL` is read **per request** rather than baked in at
 * build time.
 *
 * Not a micro-optimisation — a correctness fix, caught by curling the built
 * output: these routes are statically generated by default, so a build that ran
 * without `APP_URL` publishes a file full of `http://localhost:3000`, *silently*,
 * while page metadata (which is dynamic) shows the right origin. One container
 * image deployed to two origins would serve the wrong one in both. The cost is two
 * tiny text responses that crawlers fetch rarely.
 */
export const dynamic = 'force-dynamic'

export default function robots(): MetadataRoute.Robots {
	return {
		rules: [
			{
				userAgent: '*',
				allow: '/',
				disallow: ['/api/', '/login', '/403'],
			},
		],
		sitemap: `${siteUrl}/sitemap.xml`,
		host: siteUrl,
	}
}
