import type { MetadataRoute } from 'next'
import { absoluteUrl } from '@/core/site-url'

/**
 * Served at /sitemap.xml. Like robots.ts this covers the whole origin.
 *
 * **Only publicly reachable pages belong here.** A sitemap listing
 * `/dashboard` would be telling crawlers to fetch URLs that redirect to
 * `/login`, which is worse than omitting them: it burns crawl budget and reports
 * as an error in Search Console. Everything behind the session guard is
 * deliberately absent, and so is `/login` itself (see robots.ts on why).
 *
 * **That currently leaves it empty, and that is correct for this template.** There
 * is no publicly crawlable page: `/` is a 307 to `/dashboard` (see
 * `(app)/page.tsx`), the whole `(app)` group needs a session, and `/login` and
 * `/403` are disallowed in robots.ts. Listing `/` anyway — which this file did at
 * first — publishes a redirect, which is the exact failure `e2e/seo.e2e.ts`
 * now guards against.
 *
 * So what ships is the machinery, wired and tested, with nothing in it yet. Add
 * public routes to `PUBLIC_PATHS` as they appear; anything data-driven (a blog, a
 * product catalogue) should read from a service in `core/services/` here, the same
 * way a page would.
 */
const PUBLIC_PATHS: readonly string[] = []

/**
 * `force-dynamic` so `APP_URL` is read **per request** rather than baked in at
 * build time.
 *
 * Not a micro-optimisation — a correctness fix, caught by curling the built
 * output: these routes are statically generated by default, so a build that ran
 * without `APP_URL` publishes a file full of `http://localhost:3000`, *silently*,
 * while page metadata (which is dynamic) shows the right origin. One container
 * image deployed to two origins would serve the wrong one in both. The cost is two
 * tiny text responses that crawlers fetch rarely.
 */
export const dynamic = 'force-dynamic'

export default function sitemap(): MetadataRoute.Sitemap {
	return PUBLIC_PATHS.map((path) => ({
		url: absoluteUrl(path),
		// `lastModified` is honest only if it tracks the content. A static `new Date()`
		// claims every page changed on every build, which crawlers learn to ignore —
		// so it's set from the data for data-driven routes and left off here.
		changeFrequency: 'monthly',
		priority: 1,
	}))
}
